# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='genre',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
