# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_stock_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
