# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_stock_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Movie',
        ),
    ]
